apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-pvc

# pvc 문법
spec:
  storageClassName: my-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

