apiVersion: v1
kind: PersistentVolume

metadata:
  name: mysql-pv

# pvc 문법
spec:
  storageClassName: my-storage
  capacity:
    # 용량설정
    storage: 1Gi
    # 접근모드 
  accessModes:
    - ReadWriteOnce
    # hostPath를 쓰고 싶을떄 ReadWriteOnce 이 모드로 밖에 안됨  
  hostPath:
    path: "/mnt/data"

